# Generated by Django 4.2.2 on 2023-07-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('neighbourhood_key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=3)),
                ('image', models.FilePathField(path='/media/uploads', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('vote_key', models.IntegerField(primary_key=True, serialize=False)),
                ('user_info', models.CharField(max_length=200)),
                ('vote_time', models.DateTimeField(verbose_name='Timestamp when user submitted')),
                ('neighbourhood_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.neighbourhood')),
            ],
        ),
    ]
